name: firebase_auth_rest
description: A platform independent Dart/Flutter Wrapper for the Firebase
  Authentication API based on REST
version: 0.1.1
homepage: https://github.com/Skycoder42/firebase_auth_rest

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2
  json_annotation: ^3.0.1
  freezed_annotation: ^0.11.0+1
  logger: ^0.9.2

dev_dependencies:
  test: ^1.15.3
  build_runner: ^1.10.1
  json_serializable: ^3.4.0
  freezed: ^0.11.5
  lint: ^1.2.0
  mockito: ^4.1.1
  test_coverage: ^0.4.3
  cider: ^0.0.5
  git_hooks: ^0.0.4
  path: ^1.7.0
