name: firebase_auth_rest
description: A platform independent Dart/Flutter Wrapper for the Firebase
  Authentication API based on REST
version: 2.0.0
homepage: https://github.com/Skycoder42/firebase_auth_rest

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  freezed_annotation: ^0.14.1
  http: ^0.13.2
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.0.1
  coverage: ^1.0.2
  dart_pre_commit: ^2.3.0
  freezed: ^0.14.1+3
  json_serializable: ^4.1.1
  lint: ^1.5.3
  mockito: ^5.0.7
  test: ^1.17.3
  tuple: ^2.0.0
